### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by DaBultz**
This PR adds the discussed changes we had on Discord, below I list overview of the changes; as well as a discussion section about further small changes 

I think I managed to document everything

## Symbols

For symbols I wanted to keep it simple and yet informative. 
🌟 - The project is recommended by the community

🔨 - The project is actively maintained

## Formatting

The formatting is now: 
```
<link> `<language>` - <summary>
```
this looks neater in my opinion and should make it more natural sounding for when screen readers are used. 

multiple languages should be used when there's a close to even split of 2 or more languages see, e.g: [https://github.com/wrenger/snork](https://github.com/wrenger/snork)

## Machine Learning and Data Science

**- articles and libraries are now under different headings**
Would make it easier to tell between Machine Learning Articles & Machine Learning Libraries.

# Removals 

## Battlesnake 
- [fuele/battlensake](https://github.com/fuele/battlensake)
This repo was on the list, but only contain a hello world web server in go

- [Nettogrof/battlesnake-nessegrev](https://github.com/Nettogrof/battlesnake-nessegrev)
This repo contains binaries from this one [Nettogrof/nessegrev-java-dev](https://github.com/Nettogrof/nessegrev-java-dev) I would say it's a duplicate

# Discussion 

Might be useful to have these over on discord, so it's easier for everyone to engage

1) We have a lot of battlesnakes, would it be an improvement if we were to split these by year or make headings for the most used languages and leave less used languages under a "other" heading?

### CODE REVIEW

**Comment by xtagon** [comment]
Hi @DaBultz , I left some initial review comments but this PR has a lot of different things going on at once so I will take some more time to review the diff. In the future it might be easier to open separate PRs for separate types of changes instead of one big one, but I'll work with this :)

Thanks again for contributing!

**Comment by xtagon** [comment]
This may be controversial but I don't agree with splitting up the ML section into articles vs libraries. The list is small enough right now that I prefer simplicity and the able of contents is easier to sort.

**Comment by xtagon** [comment]
After reviewing this some more, I would like to merge the formatting changes and language tags but I think we should leave the "actively maintained" and "recommended by the community" emojis for a separate PR or multiple separate PRs because it will take some more consideration to decide which ones to assign with those. Would you mind removing that legend for now and we can revisit in a second PR?

Thanks

**Comment by DaBultz** [comment]
> This may be controversial but I don't agree with splitting up the ML section into articles vs libraries. The list is small enough right now that I prefer simplicity and the able of contents is easier to sort.

In hindsight, I agree and with the added language tags it should give the same effect. 

> After reviewing this some more, I would like to merge the formatting changes and language tags but I think we should leave the "actively maintained" and "recommended by the community" emojis for a separate PR or multiple separate PRs because it will take some more consideration to decide which ones to assign with those. Would you mind removing that legend for now and we can revisit in a second PR?

I've removed the legend and reverted the machine learning changes, will be opening a new PR for the symbols.

**Comment by xtagon** [comment]
> I've removed the legend and reverted the machine learning changes, will be opening a new PR for the symbols.

Thanks, would you remove it from the TOC too please?

**Comment by DaBultz** [comment]
> Thanks, would you remove it from the TOC too please?

Totally missed that, it's now removed.

**Comment by xtagon** [comment]
I fixed a few of the other requests myself while merging so you'll need to pull the latest `main` branch into your fork to have all the changes.

Thanks again for the PR :)

**Pull request merged**
