### PR TITLE
Add symbols

### PR DESCRIPTION
**Pull request by DaBultz**
I've opened this as a draft pull request, while it's worked on.

It was requested in PR #22 that adding the symbols should be turned into a separate PR or multiple, as it takes some consideration, so for now, I've only added the legend back.

Here is how I'm thinking we could do it:

1) The legend is added + some guidelines (i.e when the symbols is added/removed)

2) A second PR is made, in which we try and update the list
2.1) Maintainers is able to let us know, that their project is maintained

This has the benefit of:
- New PR's can get the symbols 
- Developers adding their project can add the maintained symbol 
- Existing developers, can open a PR adding the maintained symbol to their projects 

I think, this approach is one of the simpler ways of doing it and when it's done. maintaining would be kept simple.

### CODE REVIEW

**Comment by xtagon** [comment]
> 🌟 - The project is recommended by the community

Everything that makes the list would be considered recommended by the community, yes?

**Comment by DaBultz** [comment]
> Everything that makes the list would be considered recommended by the community, yes?

Normally these awesome lists, gets a lot of various of projects added. So some adopt a way to set part the projects which is often recommended by the community. So when any checks the list. 

However, on a second thought. there's not really many projects you can recommend and the ones which end up being recommended end up being the ones which are actively maintained. So maybe, we don't need it and keep the actively maintained one?

**Comment by xtagon** [comment]
> However, on a second thought. there's not really many projects you can recommend and the ones which end up being recommended end up being the ones which are actively maintained. So maybe, we don't need it and keep the actively maintained one?

Yeah I agree, and if something isn't really fit to recommend we should consider removing it. I know not every list does that, but the original idea of awesome lists is careful curation :)

**Comment by DaBultz** [comment]
> Yeah I agree, and if something isn't really fit to recommend we should consider removing it. I know not every list does that, but the original idea of awesome lists is careful curation :)

I've removed the symbol and opened it up for merge, If you would you like me to go through and add the maintained symbol for the projects which appear to be maintained, I could do that.

**Comment by xtagon** [comment]
Do you have some specific ones in mind?

**Comment by DaBultz** [comment]
The only one I have in mind is the updated games downloader extension for chrome, which was merged 2 days ago and the battlesnake/rules repo

Not sure if anything else is maintained, my shameless plug would also get the actively maintained, when I feel satisfied with it's state.

**Comment by DaBultz** [comment]
@xtagon Accidently committed my shameless plug to the branch for this PR would you like me to open a new PR with my shameless plug?

**Comment by xtagon** [comment]
> @xtagon Accidently committed my shameless plug to the branch for this PR would you like me to open a new PR with my shameless plug?

Yeah makes sense for it to be separate

**Comment by DaBultz** [comment]
> > @xtagon Accidently committed my shameless plug to the branch for this PR would you like me to open a new PR with my shameless plug?
> 
> Yeah makes sense for it to be separate

Should be done :)

**Comment by xtagon** [comment]
Closing as this project has moved to https://github.com/BattlesnakeOfficial/awesome-battlesnake

**Pull request closed without merging**
